import 'package:flutter/material.dart';
import 'package:poc/theme/generated_tokens/kp_color.dart';

final lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: KpColor.primaryLight,
  onPrimary: KpColor.onPrimaryLight,
  primaryContainer: KpColor.primaryLight.withValues(alpha: 0.1),
  onPrimaryContainer: KpColor.onPrimaryLight.withValues(alpha: 0.8),
  secondary: KpColor.secondaryLight,
  onSecondary: KpColor.onSecondaryLight,
  secondaryContainer: KpColor.secondaryLight.withValues(alpha: 0.1),
  onSecondaryContainer: KpColor.onSecondaryLight.withValues(alpha: 0.8),
  tertiary: KpColor.secondaryLight,
  onTertiary: Colors.white,
  tertiaryContainer: KpColor.secondaryLight.withValues(alpha: 0.1),
  onTertiaryContainer: Colors.white.withValues(alpha: 0.8),
  error: KpColor.errorLight,
  onError: KpColor.onErrorLight,
  errorContainer: KpColor.errorLight.withValues(alpha: 0.1),
  onErrorContainer: KpColor.onErrorLight.withValues(alpha: 0.8),
  surface: KpColor.surfaceLight,
  onSurface: KpColor.textPrimaryLight,
  surfaceContainerHighest: Colors.grey.shade200,
  onSurfaceVariant: KpColor.textSecondaryLight,
  outline: KpColor.borderLight,
  shadow: Colors.black26,
  inverseSurface: KpColor.textPrimaryLight,
  onInverseSurface: KpColor.surfaceLight,
  inversePrimary: KpColor.primaryLight.withValues(alpha: 0.7),
  surfaceTint: KpColor.primaryLight,
);
