name: poc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  go_router: ^14.8.1
  url_launcher: ^6.3.1
  getwidget: ^6.0.0
  google_fonts: ^6.2.1
  color_type_converter: ^1.0.5
  riverpod_generator: ^2.6.5
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.0.0
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  very_good_analysis: ^7.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  generate: true
